// services/user-export.service.ts
import { utils, write } from "xlsx";
import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { format } from "date-fns";
import type { User } from "../types/user.types";

class UserExportService {
  // Export to CSV
  async exportToCSV(users: User[]): Promise<Blob> {
    const headers = [
      "ID",
      "Email",
      "First Name",
      "Last Name",
      "Phone",
      "Role",
      "Status",
      "Email Verified",
      "Phone Verified",
      "Total Bookings",
      "Total Spent",
      "Loyalty Points",
      "Membership Tier",
      "Last Login",
      "Created At",
    ];

    const rows = users.map((user) => [
      user.id,
      user.email,
      user.firstName,
      user.lastName,
      user.phone || "",
      user.role,
      user.isActive ? "Active" : "Inactive",
      user.emailVerified ? "Yes" : "No",
      user.phoneVerified ? "Yes" : "No",
      user.totalBookings || 0,
      user.totalSpent || 0,
      user.loyaltyPoints || 0,
      user.membershipTier || "None",
      user.lastLogin
        ? format(new Date(user.lastLogin), "yyyy-MM-dd HH:mm")
        : "Never",
      format(new Date(user.createdAt), "yyyy-MM-dd HH:mm"),
    ]);

    const csvContent = [
      headers.join(","),
      ...rows.map((row) =>
        row
          .map((cell) =>
            typeof cell === "string" && cell.includes(",") ? `"${cell}"` : cell
          )
          .join(",")
      ),
    ].join("\n");

    return new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  }

  // Export to Excel
  async exportToExcel(users: User[]): Promise<Blob> {
    const worksheet = utils.json_to_sheet(
      users.map((user) => ({
        ID: user.id,
        Email: user.email,
        "First Name": user.firstName,
        "Last Name": user.lastName,
        Phone: user.phone || "",
        Role: user.role,
        Status: user.isActive ? "Active" : "Inactive",
        "Email Verified": user.emailVerified ? "Yes" : "No",
        "Phone Verified": user.phoneVerified ? "Yes" : "No",
        "Total Bookings": user.totalBookings || 0,
        "Total Orders": user.totalOrders || 0,
        "Total Spent (KES)": user.totalSpent || 0,
        "Loyalty Points": user.loyaltyPoints || 0,
        "Membership Tier": user.membershipTier || "None",
        "Last Login": user.lastLogin
          ? format(new Date(user.lastLogin), "yyyy-MM-dd HH:mm")
          : "Never",
        "Created At": format(new Date(user.createdAt), "yyyy-MM-dd HH:mm"),
        "Updated At": format(new Date(user.updatedAt), "yyyy-MM-dd HH:mm"),
      }))
    );

    // Set column widths
    const columnWidths = [
      { wch: 20 }, // ID
      { wch: 30 }, // Email
      { wch: 15 }, // First Name
      { wch: 15 }, // Last Name
      { wch: 15 }, // Phone
      { wch: 15 }, // Role
      { wch: 10 }, // Status
      { wch: 15 }, // Email Verified
      { wch: 15 }, // Phone Verified
      { wch: 15 }, // Total Bookings
      { wch: 15 }, // Total Orders
      { wch: 20 }, // Total Spent
      { wch: 15 }, // Loyalty Points
      { wch: 15 }, // Membership
      { wch: 20 }, // Last Login
      { wch: 20 }, // Created At
      { wch: 20 }, // Updated At
    ];
    worksheet["!cols"] = columnWidths;

    const workbook = utils.book_new();
    utils.book_append_sheet(workbook, worksheet, "Users");

    const excelBuffer = write(workbook, { bookType: "xlsx", type: "array" });
    return new Blob([excelBuffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });
  }

  // Export to PDF
  async exportToPDF(users: User[]): Promise<Blob> {
    const doc = new jsPDF("landscape");

    // Add title
    doc.setFontSize(20);
    doc.text("Padel Mania - User Report", 14, 20);

    // Add metadata
    doc.setFontSize(10);
    doc.text(`Generated on: ${format(new Date(), "yyyy-MM-dd HH:mm")}`, 14, 30);
    doc.text(`Total Users: ${users.length}`, 14, 35);
    doc.text(
      `Generated by: ${localStorage.getItem("currentUserName") || "Admin"}`,
      14,
      40
    );

    // Prepare table data
    const tableHeaders = [
      "ID",
      "Name",
      "Email",
      "Phone",
      "Role",
      "Status",
      "Bookings",
      "Spent (KES)",
      "Points",
      "Joined",
    ];

    const tableData = users.map((user) => [
      user.id.substring(0, 8) + "...",
      `${user.firstName} ${user.lastName}`,
      user.email,
      user.phone || "N/A",
      user.role,
      user.isActive ? "Active" : "Inactive",
      user.totalBookings || 0,
      user.totalSpent?.toLocaleString() || "0",
      user.loyaltyPoints || 0,
      format(new Date(user.createdAt), "yyyy-MM-dd"),
    ]);

    // Add table
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (doc as any).autoTable({
      head: [tableHeaders],
      body: tableData,
      startY: 45,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [41, 128, 185] },
    });

    // Add footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.text(
        `Page ${i} of ${pageCount}`,
        doc.internal.pageSize.width - 30,
        doc.internal.pageSize.height - 10
      );
    }

    return doc.output("blob");
  }

  // Export to JSON
  async exportToJSON(users: User[]): Promise<Blob> {
    const jsonData = JSON.stringify(users, null, 2);
    return new Blob([jsonData], { type: "application/json" });
  }

  // Generate filename
  generateFilename(fileFormat: string): string {
    const timestamp = format(new Date(), "yyyy-MM-dd-HHmm");
    return `padel-mania-users-${timestamp}.${fileFormat}`;
  }

  // Download file
  downloadFile(blob: Blob, filename: string): void {
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  }
}

export const userExportService = new UserExportService();
